server:
  ssl:
    enabled: false

spring:
  config:
    import: optional:file:.env.local

logging:
  level:
    root: DEBUG

clients:
  ptv:
    username: ${PTV_API_DEVID}
    password: ${PTV_API_SECRET}
